src/TheRota/Controllers/PictureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TheRota.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace TheRota.Controllers
{
    public class PictureController : Controller
    {
        private IRotaRepository _repository;

        public PictureController(IRotaRepository repository)
        {
            _repository = repository;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            var data = _repository.GetPictures(3);
            return View(data);
        }
    }
}

src/TheRota/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>The Rota - @ViewBag.Title</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/bootswatch/yeti/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <button id="sidebarToggle" class="btn btn-primary">
                        <i class="fa fa-angle-right"></i>
                    </button>
                    <button id="colourToggle" class="btn btn-primary">
                        <i class="fa fa-star"></i>
                    </button>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="#" class="btn btn-sm btn-info">
                        <i class="fa fa-save"></i>Save
                    </a>
                </li>
                <li>
                    <a href="#" class="btn btn-sm btn-info">
                        <i class="fa fa-print"></i>Print
                    </a>
                </li>
            </ul>
            <a asp-controller="App" asp-action="Index" class="navbar-brand">The Rota</a>
        </div>
    </nav>
    <div id="sidebar">
        <ul class="nav">
            <li class="active"><a asp-controller="App" asp-action="Index">Home</a></li>
            <li><a asp-controller="App" asp-action="About">About</a></li>
            <li><a asp-controller="App" asp-action="Contact">Contact</a></li>
            <li><a asp-controller="Picture" asp-action="Index">Pictures</a></li>
            <li> </li>
        </ul>
    </div>
    <div id="wrapper">
        <div id="main" class="container-fluid">
            @RenderBody()
        </div>
    </div>
    <div id="footer" class="container-fluid">
        <div class="navbar navbar-inverse navbar-fixed-bottom">
            <h4 class="text-center text-info">&copy; 2017 - The Rota by Jeff</h4>
        </div>
    </div>

    <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    @RenderSection("scripts", false)
    <script type="text/javascript" src="~/js/site.js"></script>
</body>
</html>